name: Deploy Docs

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install MkDocs Material and Dependencies
        run: |
          pip install "mkdocs-material==9.5.3"
          pip install pymdown-extensions

      - name: Generate Dynamic Project Docs
        run: python generate_docs.py

      - name: Build and Deploy
        run: mkdocs gh-deploy --force
